from setuptools import setup, find_packages

setup(
    name="neural-audio-spring-reverb",
    version="0.3.0",
    author="Francesco Papaleo",
    description="Neural Audio Modelling Strategies for a Spring Reverb",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/francescopapaleo/neural-audio-spring-reverb",
    license='AGPL-3.0',
    package_dir={'': 'src'},
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU Affero General Public License v3',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.10',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
    install_requires=[
        "torch",
        "torchaudio",
        "torchinfo",
        "numpy",
        "matplotlib",
        "scipy",
        "h5py",
        "auraloss",
        "wandb",
        "neutone_sdk",
    ],
)
