configs = [

    {
    'conf_name': 'TCN-44k',
    'model_type': 'TCN',
    'n_channels': 64,
    'dilation': 10,
    'n_blocks': 5,
    'kernel_size': 5,
    'cond_dim': 2,
    },

    {
    'conf_name': 'TCN-test',
    'model_type': 'TCN',
    'n_channels': 32,
    'dilation': 8,
    'n_blocks': 5,
    'kernel_size': 9,
    'cond_dim': 2,
    },
    {
    'conf_name': 'WN-150',
    'model_type': 'WaveNet',
    'n_channels': 16,
    'dilation': 2,
    'num_repeat': 10,
    'kernel_size': 5,
    },
    {
    'conf_name': 'WN-1k',
    'model_type': 'WaveNet',
    'n_channels': 8,
    'dilation': 2,
    'num_repeat': 18,
    'kernel_size': 1,
    },
    {
    'conf_name': 'WN-1500',
    'model_type': 'WaveNet',
    'n_channels': 8,
    'dilation': 10,
    'num_repeat': 5,
    'kernel_size': 5,
    },
    {
    'conf_name': 'LSTM-BL',
    'model_type': 'LSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 32,
    'num_layers': 2,
    },
    {
    'conf_name': 'LSTM-32-4',
    'model_type': 'LSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 32,
    'num_layers': 4,
    },
    {
    'conf_name': 'LSTM-96-1',
    'model_type': 'LSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 96,
    'num_layers': 1,
    },
    {
    'conf_name': 'LSTM-96-2',
    'model_type': 'LSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 96,
    'num_layers': 2,
    },
    {
    'conf_name': 'BiLSTM',
    'model_type': 'BiLSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 64,
    'num_layers': 2,
    },
    {
    'conf_name': 'BiLSTM-8-gated',
    'model_type': 'BiLSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 64,
    'num_layers': 8,
    },
    {
    'conf_name': 'BiLSTM-96',
    'model_type': 'BiLSTM',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 96,
    'num_layers': 2,
    },
    
    {
    'conf_name': 'GRU',
    'model_type': 'GRU',
    'input_size': 1,
    'output_size': 1,
    'hidden_size': 96,
    'num_layers': 2,
    },
]

