source "https://rubygems.org"

# Remove the jekyll gem declaration
# gem "jekyll", "~> 4.3.3"

# Add the GitHub Pages gem
gem "github-pages", group: :jekyll_plugins

# Keep your existing plugins, they will be handled by the github-pages gem
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby specific gems
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# JRuby-specific http_parser gem
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

